import { PERMISSIONS } from "@/lib/constants";

export type PlanCode = "starter" | "business" | "enterprise";

function unique(values: string[]) {
  return Array.from(new Set(values));
}

const WORKSPACE_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.APPS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_MANAGE,
  PERMISSIONS.BILLING_VIEW,
];

const SALES_POS_PERMISSIONS = [
  PERMISSIONS.POS_USE,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.SALES_VIEW_ALL,
  PERMISSIONS.SALES_CREATE,
  PERMISSIONS.SALES_EDIT,
  PERMISSIONS.SALES_COMPLETE,
  PERMISSIONS.SALES_DRAFT,
  PERMISSIONS.SALES_REFUND,
  PERMISSIONS.SALES_PRINT,
  PERMISSIONS.SALES_RETURNS_VIEW,
  PERMISSIONS.SALES_RETURNS_MANAGE,
  PERMISSIONS.CUSTOMER_PAYMENTS_VIEW,
  PERMISSIONS.CUSTOMER_PAYMENTS_CREATE,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_CREATE,
  PERMISSIONS.CUSTOMERS_EDIT,
  PERMISSIONS.CUSTOMER_STATEMENTS_VIEW,
  PERMISSIONS.CUSTOMER_STATEMENTS_EXPORT,
  PERMISSIONS.QUOTATIONS_VIEW,
  PERMISSIONS.QUOTATIONS_CREATE,
  PERMISSIONS.QUOTATIONS_EDIT,
  PERMISSIONS.QUOTATIONS_CONVERT,
];

const PURCHASE_PERMISSIONS = [
  PERMISSIONS.PURCHASES_VIEW,
  PERMISSIONS.PURCHASES_VIEW_ALL,
  PERMISSIONS.PURCHASES_CREATE,
  PERMISSIONS.PURCHASES_EDIT,
  PERMISSIONS.PURCHASES_APPROVE,
  PERMISSIONS.PURCHASES_DRAFT,
  PERMISSIONS.PURCHASES_RECEIVE,
  PERMISSIONS.PURCHASES_CLOSE,
  PERMISSIONS.PURCHASE_RETURNS_VIEW,
  PERMISSIONS.PURCHASE_RETURNS_MANAGE,
  PERMISSIONS.SUPPLIERS_VIEW,
  PERMISSIONS.SUPPLIERS_CREATE,
  PERMISSIONS.SUPPLIERS_EDIT,
  PERMISSIONS.SUPPLIER_PAYMENTS_VIEW,
  PERMISSIONS.SUPPLIER_PAYMENTS_CREATE,
  PERMISSIONS.SUPPLIER_STATEMENTS_VIEW,
  PERMISSIONS.SUPPLIER_STATEMENTS_EXPORT,
];

const INVENTORY_VIEW_PERMISSIONS = [
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.INVENTORY_PRODUCTS_VIEW,
  PERMISSIONS.INVENTORY_CATEGORIES_VIEW,
  PERMISSIONS.INVENTORY_UNITS_VIEW,
  PERMISSIONS.INVENTORY_LOCATIONS_VIEW,
  PERMISSIONS.INVENTORY_TRANSFERS_VIEW,
  PERMISSIONS.INVENTORY_LEDGER_VIEW,
  PERMISSIONS.INVENTORY_LOW_STOCK_VIEW,
  PERMISSIONS.INVENTORY_BARCODES_VIEW,
  PERMISSIONS.INVENTORY_COST_VIEW,
];

const INVENTORY_CONTROL_PERMISSIONS = [
  PERMISSIONS.INVENTORY_CREATE,
  PERMISSIONS.INVENTORY_EDIT,
  PERMISSIONS.INVENTORY_PRODUCTS_MANAGE,
  PERMISSIONS.INVENTORY_CATEGORIES_MANAGE,
  PERMISSIONS.INVENTORY_UNITS_MANAGE,
  PERMISSIONS.INVENTORY_LOCATIONS_MANAGE,
  PERMISSIONS.INVENTORY_MAIN_RECEIVING_MANAGE,
  PERMISSIONS.INVENTORY_TRANSFERS_CREATE,
  PERMISSIONS.INVENTORY_TRANSFERS_APPROVE,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_VIEW,
  PERMISSIONS.INVENTORY_ADJUSTMENTS_CREATE,
  PERMISSIONS.INVENTORY_STOCK_COUNTS_VIEW,
  PERMISSIONS.INVENTORY_STOCK_COUNTS_MANAGE,
  PERMISSIONS.INVENTORY_BARCODES_MANAGE,
];

const FINANCE_BASIC_PERMISSIONS = [
  PERMISSIONS.EXPENSES_VIEW,
  PERMISSIONS.EXPENSES_CREATE,
  PERMISSIONS.EXPENSES_APPROVE,
  PERMISSIONS.SALES_REPORTS_VIEW,
  PERMISSIONS.INVENTORY_REPORTS_VIEW,
  PERMISSIONS.AGING_REPORTS_VIEW,
];

const FINANCE_ADVANCED_PERMISSIONS = [
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.PURCHASE_REPORTS_VIEW,
  PERMISSIONS.TAX_REPORTS_VIEW,
  PERMISSIONS.ACCOUNTING_VIEW,
  PERMISSIONS.ACCOUNTING_MANAGE,
  PERMISSIONS.ACCOUNTING_REPORTS,
  PERMISSIONS.CHART_OF_ACCOUNTS_VIEW,
  PERMISSIONS.CHART_OF_ACCOUNTS_MANAGE,
  PERMISSIONS.JOURNAL_ENTRIES_VIEW,
  PERMISSIONS.JOURNAL_ENTRIES_CREATE,
  PERMISSIONS.JOURNAL_ENTRIES_POST,
  PERMISSIONS.AR_VIEW,
  PERMISSIONS.AP_VIEW,
  PERMISSIONS.CASH_FLOW_VIEW,
  PERMISSIONS.INCOME_EXPENSE_VIEW,
  PERMISSIONS.EXPENSES_DELETE,
];

const TEAM_AND_SETTINGS_PERMISSIONS = [
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_INVITE,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.USERS_RESET_PASSWORD,
  PERMISSIONS.USERS_DISABLE,
  PERMISSIONS.ROLES_MANAGE,
  PERMISSIONS.EMPLOYEES_VIEW,
  PERMISSIONS.EMPLOYEES_MANAGE,
  PERMISSIONS.PAYROLL_VIEW,
  PERMISSIONS.PAYROLL_MANAGE,
  PERMISSIONS.COMPANY_SETTINGS_MANAGE,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_MANAGE,
  PERMISSIONS.STORES_VIEW,
  PERMISSIONS.STORES_MANAGE,
  PERMISSIONS.TEMPLATES_VIEW,
  PERMISSIONS.TEMPLATES_MANAGE,
  PERMISSIONS.TAX_SETTINGS_MANAGE,
  PERMISSIONS.BRANDING_MANAGE,
  PERMISSIONS.INTEGRATIONS_MANAGE,
  PERMISSIONS.BILLING_MANAGE,
];

const STARTER_PERMISSIONS = unique([
  ...WORKSPACE_PERMISSIONS,
  ...SALES_POS_PERMISSIONS,
  ...INVENTORY_VIEW_PERMISSIONS,
  PERMISSIONS.INVENTORY_TRANSFERS_CREATE,
  PERMISSIONS.INVENTORY_TRANSFERS_APPROVE,
  PERMISSIONS.PURCHASES_VIEW,
  PERMISSIONS.PURCHASES_CREATE,
  PERMISSIONS.PURCHASES_DRAFT,
  ...FINANCE_BASIC_PERMISSIONS,
]);

const BUSINESS_PERMISSIONS = unique([
  ...STARTER_PERMISSIONS,
  PERMISSIONS.REPORTS_VIEW,
  ...PURCHASE_PERMISSIONS,
  ...INVENTORY_CONTROL_PERMISSIONS,
  ...FINANCE_ADVANCED_PERMISSIONS,
  ...TEAM_AND_SETTINGS_PERMISSIONS,
]);

export const PLAN_PERMISSION_MAP: Record<PlanCode, string[]> = {
  starter: STARTER_PERMISSIONS,
  business: BUSINESS_PERMISSIONS,
  enterprise: Object.values(PERMISSIONS),
};

export function normalizePlanCode(code?: string | null): PlanCode {
  if (code === "business" || code === "enterprise") return code;
  return "starter";
}

export function getPlanAllowedPermissions(code?: string | null): string[] {
  return PLAN_PERMISSION_MAP[normalizePlanCode(code)];
}

export function applyPlanPermissionLimits(permissions: string[], code?: string | null): string[] {
  const allowed = new Set(getPlanAllowedPermissions(code));
  return permissions.filter((permission) => allowed.has(permission));
}

export function roleBypassesPlanLimits(role?: string | null): boolean {
  return role === "OWNER";
}

export function applyPlanPermissionLimitsForRole(
  permissions: string[],
  code?: string | null,
  role?: string | null,
): string[] {
  if (roleBypassesPlanLimits(role)) return permissions;
  return applyPlanPermissionLimits(permissions, code);
}
